Repository JuliaGPU/CUDAdrv.jl, pull requests merged in 2019-04, with the labels that each got.

#135 Use stack-based context handling.
  src/context.jl
  src/context/primary.jl
  test/context.jl
Labels: enhancement

#136 Escape stream in elapsed macro
  src/events.jl
  test/events.jl
Labels: bug

#137 Add stream creation flags
  src/stream.jl
  test/stream.jl
Labels: api coverage

#133 Add support for pinned memory.
  examples/vadd.jl
  src/devices.jl
  src/memory.jl
  src/module/global.jl
  test/array.jl
  test/execution.jl
  test/memory.jl
  test/runtests.jl
  test/util.jl
Labels: api coverage

#138 Try to unsafe_convert PtrOrCuPtr in opposite order
  src/pointer.jl
Labels: performance
